// Curated modern-physics additions; generated by scripts/build-modern.py.
(() => {
Object.assign(FIELD_META, {
  "量子场论": {
    "color": "#da97ed",
    "short": "QFT"
  },
  "等离子体": {
    "color": "#5ce1cb",
    "short": "PLASMA"
  },
  "量子信息": {
    "color": "#e5a2ff",
    "short": "QINFO"
  },
  "非线性与复杂系统": {
    "color": "#efc777",
    "short": "COMPLEX"
  },
  "计算与数学物理": {
    "color": "#a7bedb",
    "short": "COMPUTE"
  }
});
const additions = [
  {
    "id": "partition",
    "field": "热学与统计",
    "topic": "统计系综",
    "year": 1902,
    "date": "1902 年",
    "title": "正则系综与配分函数",
    "people": "吉布斯；玻尔兹曼等",
    "formula": "Z=Σᵢ exp(−βEᵢ)，pᵢ=exp(−βEᵢ)/Z，F=−k_B T ln Z",
    "summary": "配分函数把微观能级与平衡热力学联系起来。",
    "conditions": "固定温度、体积和粒子数；系统与热库弱耦合并处于平衡。",
    "variables": "β=1/(k_B T)，Eᵢ 微观态能量，F 亥姆霍兹自由能",
    "application": "热容、磁化率、分子统计",
    "significance": "提供由能谱计算宏观性质的通用起点。",
    "context": "代表节点为1902 年；关键贡献者为吉布斯；玻尔兹曼等。该年份用于排序，不表示此前没有相关先驱工作。",
    "sources": [
      {
        "title": "Feynman Lectures · 统计力学原理",
        "url": "https://www.feynmanlectures.caltech.edu/I_40.html"
      }
    ],
    "related": [
      "boltzmann",
      "gibbs-free"
    ],
    "kind": "理论／关系",
    "editorial": "本次新增 · 附参考来源"
  },
  {
    "id": "bose-einstein",
    "field": "热学与统计",
    "topic": "量子统计",
    "year": 1924,
    "date": "1924—1925 年",
    "title": "玻色–爱因斯坦分布",
    "people": "玻色、爱因斯坦",
    "formula": "n̄(E)=1/{exp[(E−μ)/(k_B T)]−1}",
    "summary": "全同玻色子的单粒子态可以被多个粒子占据。",
    "conditions": "理想玻色气体或独立准粒子；μ 不高于最低单粒子能量。",
    "variables": "n̄ 平均占据数，μ 化学势，E 单粒子能量",
    "application": "冷原子、光子和声子统计",
    "significance": "揭示量子统计与经典气体的本质差别。",
    "context": "代表节点为1924—1925 年；关键贡献者为玻色、爱因斯坦。该年份用于排序，不表示此前没有相关先驱工作。",
    "sources": [
      {
        "title": "Feynman Lectures · 全同粒子",
        "url": "https://www.feynmanlectures.caltech.edu/III_04.html"
      }
    ],
    "related": [
      "fermi-dirac",
      "bose-condensation"
    ],
    "kind": "理论／关系",
    "editorial": "本次新增 · 附参考来源"
  },
  {
    "id": "bose-condensation",
    "field": "凝聚态",
    "topic": "超流与冷原子",
    "year": 1925,
    "date": "1925 年",
    "title": "玻色–爱因斯坦凝聚",
    "people": "爱因斯坦；玻色提供统计基础",
    "formula": "N₀/N=1−(T/T_c)^(3/2)",
    "summary": "低温下宏观数量粒子占据同一量子态。",
    "conditions": "所示公式仅用于三维均匀理想气体且 T≤T_c；陷阱和相互作用改变结果。",
    "variables": "N₀ 基态粒子数，N 总粒子数，T_c 临界温度",
    "application": "冷原子模拟、物质波干涉",
    "significance": "提供研究宏观量子相干的可控平台；凝聚不自动等于超流。",
    "context": "代表节点为1925 年；关键贡献者为爱因斯坦；玻色提供统计基础。该年份用于排序，不表示此前没有相关先驱工作。",
    "sources": [
      {
        "title": "Feynman Lectures · 全同粒子",
        "url": "https://www.feynmanlectures.caltech.edu/III_04.html"
      }
    ],
    "related": [
      "bose-einstein",
      "bcs"
    ],
    "kind": "理论／关系",
    "editorial": "本次新增 · 附参考来源"
  },
  {
    "id": "third-law",
    "field": "热学与统计",
    "topic": "热力学基础",
    "year": 1906,
    "date": "1906—1911 年",
    "title": "热力学第三定律",
    "people": "能斯特；普朗克",
    "formula": "lim(T→0) S(T)=0（唯一基态的理想纯晶体）",
    "summary": "第三定律约束低温极限的熵与可达性。",
    "conditions": "零熵形式需唯一基态、平衡且无残余无序；简并基态可有残余熵。",
    "variables": "S 熵，T 绝对温度",
    "application": "低温制冷、绝对熵计算",
    "significance": "补全热力学的低温边界。",
    "context": "代表节点为1906—1911 年；关键贡献者为能斯特；普朗克。该年份用于排序，不表示此前没有相关先驱工作。",
    "sources": [
      {
        "title": "Feynman Lectures · 热力学实例",
        "url": "https://www.feynmanlectures.caltech.edu/I_45.html"
      }
    ],
    "related": [
      "zeroth",
      "second-law"
    ],
    "kind": "理论／关系",
    "editorial": "本次新增 · 附参考来源"
  },
  {
    "id": "heat-conduction",
    "field": "热学与统计",
    "topic": "输运与非平衡",
    "year": 1822,
    "date": "1822 年",
    "title": "傅里叶热传导定律",
    "people": "约瑟夫·傅里叶",
    "formula": "j_Q=−κ∇T；∂T/∂t=α∇²T",
    "summary": "温度梯度驱动热流，能量守恒产生热扩散方程。",
    "conditions": "局域平衡、线性各向同性导热；第二式还需常物性、无热源和无对流。",
    "variables": "κ 导热率，α=κ/(ρc_p) 热扩散率，j_Q 热流密度",
    "application": "散热、热防护、材料热测量",
    "significance": "连接宏观传热与偏微分方程。",
    "context": "代表节点为1822 年；关键贡献者为约瑟夫·傅里叶。该年份用于排序，不表示此前没有相关先驱工作。",
    "sources": [
      {
        "title": "Feynman Lectures · 扩散",
        "url": "https://www.feynmanlectures.caltech.edu/I_43.html"
      }
    ],
    "related": [
      "first-law",
      "fourier"
    ],
    "kind": "理论／关系",
    "editorial": "本次新增 · 附参考来源"
  },
  {
    "id": "einstein-diffusion",
    "field": "热学与统计",
    "topic": "输运与非平衡",
    "year": 1905,
    "date": "1905 年",
    "title": "爱因斯坦扩散关系",
    "people": "爱因斯坦；斯莫卢霍夫斯基独立发展",
    "formula": "⟨[x(t)−x(0)]²⟩=2Dt，D=μ_m k_B T",
    "summary": "热运动导致位移扩散，迁移率与涨落强度相关。",
    "conditions": "长于动量弛豫时间的一维正常扩散；μ_m 是速度/外力的机械迁移率。",
    "variables": "D 扩散系数，μ_m 机械迁移率",
    "application": "粒径测量、软物质、扩散输运",
    "significance": "把可见布朗运动与分子热运动联系起来。",
    "context": "代表节点为1905 年；关键贡献者为爱因斯坦；斯莫卢霍夫斯基独立发展。该年份用于排序，不表示此前没有相关先驱工作。",
    "sources": [
      {
        "title": "Feynman Lectures · 布朗运动",
        "url": "https://www.feynmanlectures.caltech.edu/I_41.html"
      }
    ],
    "related": [
      "diffusion-fick",
      "fluctuation-dissipation"
    ],
    "kind": "理论／关系",
    "editorial": "本次新增 · 附参考来源"
  },
  {
    "id": "diffusion-fick",
    "field": "热学与统计",
    "topic": "输运与非平衡",
    "year": 1855,
    "date": "1855 年",
    "title": "菲克扩散定律",
    "people": "阿道夫·菲克",
    "formula": "J=−D∇n；∂n/∂t=D∇²n",
    "summary": "浓度梯度驱动物质扩散。",
    "conditions": "局域线性输运；第二式需常 D、无反应、无对流。",
    "variables": "J 粒子通量，n 数密度，D 扩散系数",
    "application": "掺杂、膜传质、生物物理",
    "significance": "用连续方程描述随机微观运动的宏观效果。",
    "context": "代表节点为1855 年；关键贡献者为阿道夫·菲克。该年份用于排序，不表示此前没有相关先驱工作。",
    "sources": [
      {
        "title": "Feynman Lectures · 扩散",
        "url": "https://www.feynmanlectures.caltech.edu/I_43.html"
      }
    ],
    "related": [
      "einstein-diffusion"
    ],
    "kind": "理论／关系",
    "editorial": "本次新增 · 附参考来源"
  },
  {
    "id": "onsager",
    "field": "热学与统计",
    "topic": "输运与非平衡",
    "year": 1931,
    "date": "1931 年",
    "title": "昂萨格互易关系",
    "people": "拉尔斯·昂萨格",
    "formula": "Jᵢ=ΣⱼLᵢⱼXⱼ；Lᵢⱼ=Lⱼᵢ",
    "summary": "不同不可逆通量之间的线性耦合具有互易性。",
    "conditions": "近平衡与微观可逆性；所示对称式限无破坏时间反演的外场且变量时间反演奇偶性相同。",
    "variables": "Jᵢ 通量，Xⱼ 热力学力，Lᵢⱼ 输运系数",
    "application": "热电、扩散耦合、电化学",
    "significance": "约束交叉输运系数；磁场下需 Onsager–Casimir 形式。",
    "context": "代表节点为1931 年；关键贡献者为拉尔斯·昂萨格。该年份用于排序，不表示此前没有相关先驱工作。",
    "sources": [
      {
        "title": "Onsager (1931) · Reciprocal Relations I",
        "url": "https://doi.org/10.1103/PhysRev.37.405"
      }
    ],
    "related": [
      "first-law",
      "diffusion-fick"
    ],
    "kind": "理论／关系",
    "editorial": "本次新增 · 附参考来源"
  },
  {
    "id": "fluctuation-dissipation",
    "field": "热学与统计",
    "topic": "输运与非平衡",
    "year": 1951,
    "date": "1951 年",
    "title": "涨落–耗散关系",
    "people": "卡伦、韦尔顿；久保等",
    "formula": "S_xx(ω)=2k_B T Imχ(ω)/ω（经典极限）",
    "summary": "平衡涨落谱与系统对外扰动的耗散响应相连。",
    "conditions": "线性响应、热平衡；双边谱 S=∫dt exp(iωt)⟨x(t)x(0)⟩，外力耦合为 −fx。",
    "variables": "χ 位移对力的响应函数，ω 角频率；量子高频情形需修正",
    "application": "噪声测量、微流变、热涨落",
    "significance": "使无扰动测量能够推断响应特性。",
    "context": "代表节点为1951 年；关键贡献者为卡伦、韦尔顿；久保等。该年份用于排序，不表示此前没有相关先驱工作。",
    "sources": [
      {
        "title": "Callen & Welton (1951) · Irreversibility and Generalized Noise",
        "url": "https://doi.org/10.1103/PhysRev.83.34"
      }
    ],
    "related": [
      "einstein-diffusion",
      "onsager"
    ],
    "kind": "理论／关系",
    "editorial": "本次新增 · 附参考来源"
  },
  {
    "id": "density-matrix",
    "field": "量子物理",
    "topic": "量子态与测量",
    "year": 1927,
    "date": "1927 年",
    "title": "密度算符",
    "people": "冯·诺依曼、朗道等",
    "formula": "ρ=Σᵢpᵢ|ψᵢ⟩⟨ψᵢ|，⟨A⟩=Tr(ρA)",
    "summary": "统一表达纯态、统计混合和子系统状态。",
    "conditions": "ρ 为正半定算符且 Trρ=1；混合态的分解一般不唯一。",
    "variables": "pᵢ 制备概率，A 可观测算符，Tr 迹",
    "application": "开放系统、量子态层析",
    "significance": "摆脱仅用单个波函数描述系统的限制。",
    "context": "代表节点为1927 年；关键贡献者为冯·诺依曼、朗道等。该年份用于排序，不表示此前没有相关先驱工作。",
    "sources": [
      {
        "title": "Preskill · Quantum states and entanglement",
        "url": "https://www.preskill.caltech.edu/ph219/chap2_15.pdf"
      }
    ],
    "related": [
      "born-rule",
      "von-neumann-entropy"
    ],
    "kind": "理论／关系",
    "editorial": "本次新增 · 附参考来源"
  },
  {
    "id": "von-neumann-entropy",
    "field": "量子信息",
    "topic": "量子态与纠缠",
    "year": 1927,
    "date": "1927 年",
    "title": "冯·诺依曼熵",
    "people": "约翰·冯·诺依曼",
    "formula": "S(ρ)=−Tr(ρ log₂ρ)",
    "summary": "量化量子混合程度；双体纯态的约化熵可量化纠缠。",
    "conditions": "以 bit 为单位；热力学熵使用 −k_B Tr(ρ lnρ)。混合双体态不能直接把约化熵等同纠缠。",
    "variables": "ρ 密度矩阵，约定 0 log 0=0",
    "application": "量子信息、纠缠分析",
    "significance": "连接信息论、统计物理与量子态结构。",
    "context": "代表节点为1927 年；关键贡献者为约翰·冯·诺依曼。该年份用于排序，不表示此前没有相关先驱工作。",
    "sources": [
      {
        "title": "Preskill · Quantum states and entanglement",
        "url": "https://www.preskill.caltech.edu/ph219/chap2_15.pdf"
      }
    ],
    "related": [
      "density-matrix",
      "boltzmann"
    ],
    "kind": "理论／关系",
    "editorial": "本次新增 · 附参考来源"
  },
  {
    "id": "ehrenfest",
    "field": "量子物理",
    "topic": "量子与经典对应",
    "year": 1927,
    "date": "1927 年",
    "title": "埃伦费斯特定理",
    "people": "保罗·埃伦费斯特",
    "formula": "d⟨x⟩/dt=⟨p⟩/m，d⟨p⟩/dt=−⟨∂V/∂x⟩",
    "summary": "量子期望值服从与经典力学相似的演化关系。",
    "conditions": "非相对论 H=p²/(2m)+V(x)；一般不成立 ⟨V′(x)⟩=V′(⟨x⟩)。",
    "variables": "x 位置，p 动量，V 势能",
    "application": "波包运动、半经典近似",
    "significance": "说明经典轨迹何时可从量子理论近似恢复。",
    "context": "代表节点为1927 年；关键贡献者为保罗·埃伦费斯特。该年份用于排序，不表示此前没有相关先驱工作。",
    "sources": [
      {
        "title": "Feynman Lectures · 算符",
        "url": "https://www.feynmanlectures.caltech.edu/III_20.html"
      }
    ],
    "related": [
      "heisenberg-eq",
      "newton-laws"
    ],
    "kind": "理论／关系",
    "editorial": "本次新增 · 附参考来源"
  },
  {
    "id": "quantum-variational",
    "field": "量子物理",
    "topic": "近似与计算",
    "year": 1909,
    "date": "1909 年数学方法；1920年代量子应用",
    "title": "量子变分原理",
    "people": "瑞利、里兹；量子力学中后续应用",
    "formula": "⟨ψ|H|ψ⟩/⟨ψ|ψ⟩≥E₀",
    "summary": "试探态的平均能量给出基态能量上界。",
    "conditions": "H 自伴且有下界；试探态须属于算符定义域，不能为零。",
    "variables": "E₀ 基态能量，ψ 试探波函数",
    "application": "原子分子、多体基态、变分量子算法",
    "significance": "把求基态转为优化问题；1909 是里兹方法节点，非量子力学创立年。",
    "context": "代表节点为1909 年数学方法；1920年代量子应用；关键贡献者为瑞利、里兹；量子力学中后续应用。该年份用于排序，不表示此前没有相关先驱工作。",
    "sources": [
      {
        "title": "Feynman Lectures · 算符",
        "url": "https://www.feynmanlectures.caltech.edu/III_20.html"
      },
      {
        "title": "Capelle · Density-functional theory",
        "url": "https://arxiv.org/abs/cond-mat/0211443"
      }
    ],
    "related": [
      "schrodinger",
      "dft-kohn-sham"
    ],
    "kind": "理论／关系",
    "editorial": "本次新增 · 附参考来源"
  },
  {
    "id": "rabi",
    "field": "量子物理",
    "topic": "原子与量子控制",
    "year": 1937,
    "date": "1937 年",
    "title": "拉比振荡",
    "people": "伊西多·拉比",
    "formula": "P_e(t)=sin²(Ωt/2)（共振）",
    "summary": "相干驱动使两能级系统的布居周期交换。",
    "conditions": "初态为基态、共振、旋波近似；无显著退相干。",
    "variables": "Ω 拉比角频率，P_e 激发态概率",
    "application": "原子钟、核磁共振、量子比特控制",
    "significance": "把量子跃迁变成可控的相干操作。",
    "context": "代表节点为1937 年；关键贡献者为伊西多·拉比。该年份用于排序，不表示此前没有相关先驱工作。",
    "sources": [
      {
        "title": "Feynman Lectures · 氨分子微波激射器",
        "url": "https://www.feynmanlectures.caltech.edu/III_09.html"
      }
    ],
    "related": [
      "born-rule",
      "density-matrix"
    ],
    "kind": "理论／关系",
    "editorial": "本次新增 · 附参考来源"
  },
  {
    "id": "berry-phase",
    "field": "量子物理",
    "topic": "几何相位",
    "year": 1984,
    "date": "1984 年",
    "title": "贝里相位",
    "people": "迈克尔·贝里；潘查拉特南等有先驱贡献",
    "formula": "γ_n=i∮⟨n(R)|∇_R n(R)⟩·dR",
    "summary": "绝热闭合演化除动力学相位外还产生几何相位。",
    "conditions": "非简并、能隙未闭合且绝热演化；简并情况需非阿贝尔推广。",
    "variables": "R 控制参数，γ_n 几何相位（模 2π）",
    "application": "拓扑材料、量子干涉、几何控制",
    "significance": "把量子态的几何结构变成可观测效应。",
    "context": "代表节点为1984 年；关键贡献者为迈克尔·贝里；潘查拉特南等有先驱贡献。该年份用于排序，不表示此前没有相关先驱工作。",
    "sources": [
      {
        "title": "Xiao, Chang & Niu · Berry Phase Effects",
        "url": "https://arxiv.org/abs/0907.2021"
      }
    ],
    "related": [
      "band-theory",
      "quantum-hall"
    ],
    "kind": "理论／关系",
    "editorial": "本次新增 · 附参考来源"
  },
  {
    "id": "london",
    "field": "凝聚态",
    "topic": "超导",
    "year": 1935,
    "date": "1935 年",
    "title": "伦敦方程与穿透深度",
    "people": "弗里茨·伦敦、海因茨·伦敦",
    "formula": "∇²B=B/λ_L²，λ_L=√[m*/(μ₀n_s q*²)]",
    "summary": "超导电流屏蔽体内磁场，产生有限穿透深度。",
    "conditions": "局域伦敦极限，远离涡旋核；n_s、m*、q* 必须采用一致的载流子约定。",
    "variables": "λ_L 穿透深度，n_s 超流载流子数密度",
    "application": "超导磁屏蔽、微波谐振器",
    "significance": "在唯象层面解释迈斯纳效应。",
    "context": "代表节点为1935 年；关键贡献者为弗里茨·伦敦、海因茨·伦敦。该年份用于排序，不表示此前没有相关先驱工作。",
    "sources": [
      {
        "title": "Feynman Lectures · 超导",
        "url": "https://www.feynmanlectures.caltech.edu/III_21.html"
      }
    ],
    "related": [
      "bcs",
      "g-l"
    ],
    "kind": "理论／关系",
    "editorial": "本次新增 · 附参考来源"
  },
  {
    "id": "g-l",
    "field": "凝聚态",
    "topic": "超导",
    "year": 1950,
    "date": "1950 年",
    "title": "金兹堡–朗道超导理论",
    "people": "金兹堡、朗道",
    "formula": "f=α|ψ|²+(β/2)|ψ|⁴+|(-iℏ∇−q*A)ψ|²/(2m*)+B²/(2μ₀)",
    "summary": "以复序参量和自由能泛函描述超导。",
    "conditions": "通常为临界温度附近的长波长展开；β>0，ψ 的归一化采用一致约定。",
    "variables": "ψ 序参量，A 矢势，α、β 展开系数",
    "application": "涡旋、临界场、超导器件",
    "significance": "连接对称性破缺、磁场和宏观量子态。",
    "context": "代表节点为1950 年；关键贡献者为金兹堡、朗道。该年份用于排序，不表示此前没有相关先驱工作。",
    "sources": [
      {
        "title": "Ginzburg · Nobel lecture: superconductivity and superfluidity",
        "url": "https://doi.org/10.1103/RevModPhys.76.981"
      }
    ],
    "related": [
      "landau-phase",
      "london"
    ],
    "kind": "理论／关系",
    "editorial": "本次新增 · 附参考来源"
  },
  {
    "id": "josephson",
    "field": "凝聚态",
    "topic": "超导",
    "year": 1962,
    "date": "1962 年",
    "title": "约瑟夫森效应",
    "people": "布赖恩·约瑟夫森",
    "formula": "I=I_c sinφ，dφ/dt=2eV/ℏ",
    "summary": "两个弱连接超导体通过相位差产生超流。",
    "conditions": "常规弱连接及正弦电流相位关系；复杂结可能含高次谐波。",
    "variables": "φ 规范不变相位差，I_c 临界电流，V 电压",
    "application": "SQUID、电压基准、超导量子比特",
    "significance": "把相位相干直接转为电学测量。",
    "context": "代表节点为1962 年；关键贡献者为布赖恩·约瑟夫森。该年份用于排序，不表示此前没有相关先驱工作。",
    "sources": [
      {
        "title": "Feynman Lectures · 超导",
        "url": "https://www.feynmanlectures.caltech.edu/III_21.html"
      }
    ],
    "related": [
      "bcs",
      "rabi"
    ],
    "kind": "理论／关系",
    "editorial": "本次新增 · 附参考来源"
  },
  {
    "id": "quantum-hall",
    "field": "凝聚态",
    "topic": "拓扑与输运",
    "year": 1980,
    "date": "1980 年",
    "title": "整数量子霍尔效应",
    "people": "克劳斯·冯·克利青等；TKNN 等解释拓扑结构",
    "formula": "σ_xy=C e²/h，C∈ℤ",
    "summary": "二维电子体系出现量子化横向电导。",
    "conditions": "低温、强磁场的量子霍尔平台；纵向电导趋零，C 的符号随约定。",
    "variables": "C 占据能带总陈数，σ_xy 霍尔电导",
    "application": "电阻基准、拓扑输运",
    "significance": "把整数拓扑量与高精度测量联系起来。",
    "context": "代表节点为1980 年；关键贡献者为克劳斯·冯·克利青等；TKNN 等解释拓扑结构。该年份用于排序，不表示此前没有相关先驱工作。",
    "sources": [
      {
        "title": "von Klitzing et al. (1980) · Quantized Hall resistance",
        "url": "https://doi.org/10.1103/PhysRevLett.45.494"
      },
      {
        "title": "Xiao, Chang & Niu · Berry Phase Effects",
        "url": "https://arxiv.org/abs/0907.2021"
      }
    ],
    "related": [
      "hall",
      "berry-phase"
    ],
    "kind": "理论／关系",
    "editorial": "本次新增 · 附参考来源"
  },
  {
    "id": "bkt",
    "field": "凝聚态",
    "topic": "相变与拓扑",
    "year": 1971,
    "date": "1971—1973 年",
    "title": "BKT 相变",
    "people": "别列津斯基、科斯特利茨、索利斯",
    "formula": "ξ≈ξ₀ exp[b/√(T/T_BKT−1)]（从高温侧趋近）",
    "summary": "二维体系中涡旋对解缚导致拓扑相变。",
    "conditions": "二维、短程相互作用、连续 U(1) 对称的相应模型；并非普通幂律临界行为。",
    "variables": "ξ 关联长度，b 非普适常数，T_BKT 转变温度",
    "application": "薄膜超流、二维磁体、冷原子",
    "significance": "说明局域序参量之外也存在相变机制。",
    "context": "代表节点为1971—1973 年；关键贡献者为别列津斯基、科斯特利茨、索利斯。该年份用于排序，不表示此前没有相关先驱工作。",
    "sources": [
      {
        "title": "Kosterlitz & Thouless (1973) · Ordering in two dimensions",
        "url": "https://doi.org/10.1088/0022-3719/6/7/010"
      }
    ],
    "related": [
      "landau-phase",
      "ising"
    ],
    "kind": "理论／关系",
    "editorial": "本次新增 · 附参考来源"
  },
  {
    "id": "dft-kohn-sham",
    "field": "凝聚态",
    "topic": "电子结构",
    "year": 1964,
    "date": "1964—1965 年",
    "title": "密度泛函理论与 Kohn–Sham 方程",
    "people": "霍恩贝格、科恩、沈吕九",
    "formula": "[−ℏ²∇²/(2m)+v_eff[n]]φᵢ=εᵢφᵢ；n=Σᵢfᵢ|φᵢ|²",
    "summary": "以电子密度求解多电子基态，辅助轨道用于自洽计算。",
    "conditions": "基态理论；实际结果取决于交换关联近似。Kohn–Sham 本征值不能普遍当作真实激发能。",
    "variables": "n 电子密度，fᵢ 占据数，v_eff 有效势",
    "application": "材料设计、分子结构、能带计算",
    "significance": "使第一性原理电子结构计算成为常用工具。",
    "context": "代表节点为1964—1965 年；关键贡献者为霍恩贝格、科恩、沈吕九。该年份用于排序，不表示此前没有相关先驱工作。",
    "sources": [
      {
        "title": "Capelle · Density-functional theory",
        "url": "https://arxiv.org/abs/cond-mat/0211443"
      }
    ],
    "related": [
      "quantum-variational",
      "band-theory"
    ],
    "kind": "理论／关系",
    "editorial": "本次新增 · 附参考来源"
  },
  {
    "id": "interval",
    "field": "相对论",
    "topic": "相对论时空",
    "year": 1908,
    "date": "1908 年",
    "title": "闵可夫斯基时空间隔",
    "people": "赫尔曼·闵可夫斯基",
    "formula": "ds²=−c²dt²+dx²+dy²+dz²",
    "summary": "洛伦兹变换保持四维时空间隔不变。",
    "conditions": "平直时空；采用 (−,+,+,+) 度规号差，类时路径 dτ²=−ds²/c²。",
    "variables": "ds 间隔，τ 固有时，c 光速",
    "application": "相对论运动学、粒子寿命",
    "significance": "以几何语言统一时间和空间。",
    "context": "代表节点为1908 年；关键贡献者为赫尔曼·闵可夫斯基。该年份用于排序，不表示此前没有相关先驱工作。",
    "sources": [
      {
        "title": "Carroll · General Relativity",
        "url": "https://arxiv.org/abs/gr-qc/9712019"
      }
    ],
    "related": [
      "lorentz-transform",
      "time-dilation"
    ],
    "kind": "理论／关系",
    "editorial": "本次新增 · 附参考来源"
  },
  {
    "id": "einstein-hilbert",
    "field": "相对论",
    "topic": "引力场论",
    "year": 1915,
    "date": "1915 年",
    "title": "爱因斯坦–希尔伯特作用量",
    "people": "希尔伯特、爱因斯坦",
    "formula": "S_g=[c³/(16πG)]∫(R−2Λ)√(−g)d⁴x",
    "summary": "对度规变分可导出爱因斯坦场方程。",
    "conditions": "x⁰=ct；完整变分须处理边界项，并加入物质作用量。",
    "variables": "R 标量曲率，g 度规行列式，Λ 宇宙学常数",
    "application": "引力理论、数值相对论",
    "significance": "将引力置于作用量和对称性的统一框架。",
    "context": "代表节点为1915 年；关键贡献者为希尔伯特、爱因斯坦。该年份用于排序，不表示此前没有相关先驱工作。",
    "sources": [
      {
        "title": "Carroll · General Relativity",
        "url": "https://arxiv.org/abs/gr-qc/9712019"
      }
    ],
    "related": [
      "general-relativity",
      "noether"
    ],
    "kind": "理论／关系",
    "editorial": "本次新增 · 附参考来源"
  },
  {
    "id": "gravitational-waves",
    "field": "相对论",
    "topic": "引力辐射",
    "year": 1916,
    "date": "1916 年预言；2015 年直接探测",
    "title": "引力波与四极矩辐射",
    "people": "爱因斯坦；LIGO/Virgo 合作组",
    "formula": "P=G⟨Q⃛ᵢⱼQ⃛ᵢⱼ⟩/(5c⁵)",
    "summary": "变化的质量四极矩能够向外辐射引力波。",
    "conditions": "公式适用于慢速弱场源；Qᵢⱼ 为去迹质量四极矩，重复指标求和。强场并合需更完整模型。",
    "variables": "P 辐射功率，Q⃛ 三阶时间导数",
    "application": "双星演化、引力波天文学",
    "significance": "1916年理论预言；2015年首次直接探测，2016年发表。",
    "context": "代表节点为1916 年预言；2015 年直接探测；关键贡献者为爱因斯坦；LIGO/Virgo 合作组。该年份用于排序，不表示此前没有相关先驱工作。",
    "sources": [
      {
        "title": "LIGO/Virgo · 引力波首次直接探测",
        "url": "https://arxiv.org/abs/1602.03837"
      },
      {
        "title": "Carroll · General Relativity",
        "url": "https://arxiv.org/abs/gr-qc/9712019"
      }
    ],
    "related": [
      "general-relativity",
      "schwarzschild"
    ],
    "kind": "理论／关系",
    "editorial": "本次新增 · 附参考来源"
  },
  {
    "id": "flrw",
    "field": "天体与宇宙",
    "topic": "宇宙学背景",
    "year": 1922,
    "date": "1922—1937 年",
    "title": "FLRW 时空",
    "people": "弗里德曼、勒梅特、罗伯逊、沃克",
    "formula": "ds²=−c²dt²+a²(t)[dr²/(1−kr²)+r²dΩ²]",
    "summary": "以均匀、各向同性的几何描述宇宙大尺度背景。",
    "conditions": "宇宙学原理的背景近似；不描述星系附近的局部非均匀结构。",
    "variables": "a 尺度因子，k 空间曲率参数，r 共动径向坐标",
    "application": "宇宙膨胀、距离关系",
    "significance": "为膨胀宇宙建立几何基础。",
    "context": "代表节点为1922—1937 年；关键贡献者为弗里德曼、勒梅特、罗伯逊、沃克。该年份用于排序，不表示此前没有相关先驱工作。",
    "sources": [
      {
        "title": "PDG 2025 Review · 大爆炸宇宙学",
        "url": "https://pdg.lbl.gov/2025/reviews/rpp2025-rev-bbang-cosmology.pdf"
      }
    ],
    "related": [
      "big-bang",
      "general-relativity"
    ],
    "kind": "理论／关系",
    "editorial": "本次新增 · 附参考来源"
  },
  {
    "id": "cosmological-redshift",
    "field": "天体与宇宙",
    "topic": "宇宙学观测",
    "year": 1927,
    "date": "1927 年",
    "title": "宇宙学红移",
    "people": "勒梅特等",
    "formula": "1+z=a(t₀)/a(t_em)",
    "summary": "光在宇宙膨胀过程中波长随尺度因子伸长。",
    "conditions": "FLRW 背景下共动发射者与观测者；实际观测还含本动速度和局部引力效应。",
    "variables": "z 红移，t_em 发射时刻，t₀ 接收时刻",
    "application": "星系巡天、宇宙距离",
    "significance": "避免把高红移直接当作狭义相对论退行速度。",
    "context": "代表节点为1927 年；关键贡献者为勒梅特等。该年份用于排序，不表示此前没有相关先驱工作。",
    "sources": [
      {
        "title": "PDG 2025 Review · 大爆炸宇宙学",
        "url": "https://pdg.lbl.gov/2025/reviews/rpp2025-rev-bbang-cosmology.pdf"
      }
    ],
    "related": [
      "flrw",
      "hubble-law"
    ],
    "kind": "理论／关系",
    "editorial": "本次新增 · 附参考来源"
  },
  {
    "id": "lcdm",
    "field": "天体与宇宙",
    "topic": "宇宙学模型",
    "year": 1990,
    "date": "1990年代形成；后续精密检验",
    "title": "ΛCDM 宇宙学基准模型",
    "people": "多代宇宙学研究者共同发展",
    "formula": "H²/H₀²=Ω_r a⁻⁴+Ω_m a⁻³+Ω_k a⁻²+Ω_Λ",
    "summary": "用普通物质、冷暗物质、辐射和宇宙学常数描述背景膨胀。",
    "conditions": "a₀=1；所示项按理想组分标度；精密中微子处理更复杂，暗物质微观本质仍未知。",
    "variables": "Ω 各组分当前密度参数，H 哈勃参数",
    "application": "CMB、BAO、超新星联合分析",
    "significance": "提供跨观测的基准模型，并非已知全部宇宙成分的微观理论。",
    "context": "代表节点为1990年代形成；后续精密检验；关键贡献者为多代宇宙学研究者共同发展。该年份用于排序，不表示此前没有相关先驱工作。",
    "sources": [
      {
        "title": "PDG 2025 Review · 宇宙学参数",
        "url": "https://pdg.lbl.gov/2025/reviews/rpp2025-rev-cosmological-parameters.pdf"
      }
    ],
    "related": [
      "flrw",
      "dark-energy"
    ],
    "kind": "观测支持的基准模型",
    "editorial": "本次新增 · 附参考来源"
  },
  {
    "id": "inflation",
    "field": "天体与宇宙",
    "topic": "早期宇宙",
    "year": 1981,
    "date": "1980—1982 年",
    "title": "宇宙暴胀",
    "people": "古斯；斯塔罗宾斯基、林德等",
    "formula": "ä>0，ε_H=−Ḣ/H²<1",
    "summary": "早期加速膨胀可解释平直性，并产生结构形成的初始扰动。",
    "conditions": "暴胀是一类模型；具体驱动场及势能尚未确认，不能与热大爆炸的观测证据等同。",
    "variables": "H=ȧ/a，ε_H 膨胀速率变化参数",
    "application": "原初扰动、CMB 模型检验",
    "significance": "把早期宇宙演化与量子涨落联系起来。",
    "context": "代表节点为1980—1982 年；关键贡献者为古斯；斯塔罗宾斯基、林德等。该年份用于排序，不表示此前没有相关先驱工作。",
    "sources": [
      {
        "title": "Baumann · TASI Lectures on Inflation",
        "url": "https://arxiv.org/abs/0907.5424"
      }
    ],
    "related": [
      "flrw",
      "lcdm"
    ],
    "kind": "待验证模型族",
    "editorial": "本次新增 · 附参考来源"
  },
  {
    "id": "klein-gordon",
    "field": "量子场论",
    "topic": "相对论量子场",
    "year": 1926,
    "date": "1926 年",
    "title": "克莱因–戈尔登方程",
    "people": "克莱因、戈尔登等",
    "formula": "[(1/c²)∂²_t−∇²+(mc/ℏ)²]φ=0",
    "summary": "自由标量场满足相对论能量动量关系。",
    "conditions": "自由自旋零场；|φ|² 不能直接解释为单粒子位置概率密度。",
    "variables": "φ 标量场，m 质量",
    "application": "标量粒子、场量子化",
    "significance": "引出粒子与反粒子并存的场论描述。",
    "context": "代表节点为1926 年；关键贡献者为克莱因、戈尔登等。该年份用于排序，不表示此前没有相关先驱工作。",
    "sources": [
      {
        "title": "Coleman · Quantum Field Theory",
        "url": "https://arxiv.org/abs/1110.5013"
      }
    ],
    "related": [
      "rel-energy-momentum",
      "dirac"
    ],
    "kind": "理论／关系",
    "editorial": "本次新增 · 附参考来源"
  },
  {
    "id": "canonical-quantization",
    "field": "量子场论",
    "topic": "场量子化",
    "year": 1927,
    "date": "1927 年",
    "title": "场的正则量子化",
    "people": "狄拉克；海森堡、泡利等",
    "formula": "[φ(t,x),π(t,y)]=iℏδ³(x−y)",
    "summary": "把经典场及其共轭动量提升为算符。",
    "conditions": "所示关系用于玻色标量场；费米场使用反对易关系，规范场须处理约束。",
    "variables": "π 共轭动量，δ³ 三维狄拉克δ函数",
    "application": "粒子产生湮灭、量子光学",
    "significance": "使粒子数变化成为理论内在过程。",
    "context": "代表节点为1927 年；关键贡献者为狄拉克；海森堡、泡利等。该年份用于排序，不表示此前没有相关先驱工作。",
    "sources": [
      {
        "title": "Coleman · Quantum Field Theory",
        "url": "https://arxiv.org/abs/1110.5013"
      }
    ],
    "related": [
      "hamilton",
      "klein-gordon"
    ],
    "kind": "理论／关系",
    "editorial": "本次新增 · 附参考来源"
  },
  {
    "id": "qed",
    "field": "量子场论",
    "topic": "规范相互作用",
    "year": 1948,
    "date": "1947—1949 年",
    "title": "量子电动力学 QED",
    "people": "朝永振一郎、施温格、费曼、戴森等",
    "formula": "ℒ=−¼F_μνF^μν+ψ̄(iγ^μD_μ−m)ψ",
    "summary": "描述带电费米子与电磁场的量子相互作用。",
    "conditions": "此处 ℏ=c=1，D_μ=∂_μ+iqA_μ；可作弱耦合微扰展开。",
    "variables": "F_μν 电磁场张量，ψ 费米场，q 电荷耦合",
    "application": "精密谱学、散射、磁矩",
    "significance": "建立极高精度的可重整化量子场论范例。",
    "context": "代表节点为1947—1949 年；关键贡献者为朝永振一郎、施温格、费曼、戴森等。该年份用于排序，不表示此前没有相关先驱工作。",
    "sources": [
      {
        "title": "Coleman · Quantum Field Theory",
        "url": "https://arxiv.org/abs/1110.5013"
      }
    ],
    "related": [
      "maxwell",
      "dirac"
    ],
    "kind": "理论／关系",
    "editorial": "本次新增 · 附参考来源"
  },
  {
    "id": "yang-mills",
    "field": "量子场论",
    "topic": "规范相互作用",
    "year": 1954,
    "date": "1954 年",
    "title": "杨–米尔斯规范理论",
    "people": "杨振宁、罗伯特·米尔斯",
    "formula": "ℒ=−¼Fᵃ_μνFᵃμν；Fᵃ_μν=∂_μAᵃ_ν−∂_νAᵃ_μ+g fᵃᵇᶜAᵇ_μAᶜ_ν",
    "summary": "非阿贝尔规范场能够自相互作用。",
    "conditions": "ℏ=c=1；生成元和耦合符号需一致；规范对称性是描述冗余而非可直接观测的自由度。",
    "variables": "fᵃᵇᶜ 结构常数，g 耦合，Aᵃ_μ 规范势",
    "application": "QCD、电弱理论",
    "significance": "构成标准模型规范相互作用的数学骨架。",
    "context": "代表节点为1954 年；关键贡献者为杨振宁、罗伯特·米尔斯。该年份用于排序，不表示此前没有相关先驱工作。",
    "sources": [
      {
        "title": "PDG 2025 Review · 量子色动力学",
        "url": "https://pdg.lbl.gov/2025/reviews/rpp2025-rev-qcd.pdf"
      }
    ],
    "related": [
      "qed",
      "standard-model"
    ],
    "kind": "理论／关系",
    "editorial": "本次新增 · 附参考来源"
  },
  {
    "id": "qcd-asymptotic",
    "field": "量子场论",
    "topic": "强相互作用",
    "year": 1973,
    "date": "1973 年",
    "title": "QCD 与渐近自由",
    "people": "格罗斯、维尔切克、波利策；盖尔曼等",
    "formula": "α_s(Q)≈4π/[(11−2n_f/3)ln(Q²/Λ_QCD²)]",
    "summary": "夸克与胶子的强耦合在高能标减弱。",
    "conditions": "SU(3) 一圈近似且 Q 远大于 Λ_QCD；n_f 为活跃夸克味数，低能不能使用此公式。",
    "variables": "Q 重整化能标，α_s 强耦合常数",
    "application": "强子碰撞、喷注、核子结构",
    "significance": "解释高能近自由行为，低能禁闭仍需非微扰方法。",
    "context": "代表节点为1973 年；关键贡献者为格罗斯、维尔切克、波利策；盖尔曼等。该年份用于排序，不表示此前没有相关先驱工作。",
    "sources": [
      {
        "title": "PDG 2025 Review · 量子色动力学",
        "url": "https://pdg.lbl.gov/2025/reviews/rpp2025-rev-qcd.pdf"
      }
    ],
    "related": [
      "yang-mills",
      "standard-model"
    ],
    "kind": "理论／关系",
    "editorial": "本次新增 · 附参考来源"
  },
  {
    "id": "electroweak",
    "field": "量子场论",
    "topic": "电弱相互作用",
    "year": 1967,
    "date": "1961—1968 年",
    "title": "电弱统一",
    "people": "格拉肖、温伯格、萨拉姆",
    "formula": "m_W=gv/2，m_Z=v√(g²+g′²)/2，e=g sinθ_W",
    "summary": "以 SU(2)_L×U(1)_Y 与自发对称性破缺统一弱作用和电磁作用。",
    "conditions": "自然单位；所示质量关系为树级，精密比较需辐射修正。",
    "variables": "g、g′ 耦合，v 真空期望值，θ_W 弱混合角",
    "application": "W/Z 过程、精密电弱检验",
    "significance": "建立可实验检验的统一规范理论。",
    "context": "代表节点为1961—1968 年；关键贡献者为格拉肖、温伯格、萨拉姆。该年份用于排序，不表示此前没有相关先驱工作。",
    "sources": [
      {
        "title": "PDG 2025 Review · 电弱模型",
        "url": "https://pdg.lbl.gov/2025/reviews/rpp2025-rev-standard-model.pdf"
      }
    ],
    "related": [
      "higgs",
      "qed"
    ],
    "kind": "理论／关系",
    "editorial": "本次新增 · 附参考来源"
  },
  {
    "id": "debye-screening",
    "field": "等离子体",
    "topic": "屏蔽与尺度",
    "year": 1923,
    "date": "1923 年",
    "title": "德拜屏蔽",
    "people": "德拜、休克尔；后推广到等离子体",
    "formula": "λ_De=√[ε₀k_B T_e/(n_e e²)]",
    "summary": "电子重排在德拜尺度上屏蔽缓慢静电扰动。",
    "conditions": "弱耦合、近麦克斯韦分布、小电势；所示为电子德拜长度，各组分贡献按倒平方相加。",
    "variables": "T_e 电子温度，n_e 电子数密度",
    "application": "放电、聚变、电离层",
    "significance": "定义集体电荷屏蔽的基本长度。",
    "context": "代表节点为1923 年；关键贡献者为德拜、休克尔；后推广到等离子体。该年份用于排序，不表示此前没有相关先驱工作。",
    "sources": [
      {
        "title": "MIT · Introduction to Plasma Physics I, course notes",
        "url": "https://ocw.mit.edu/courses/22-611j-introduction-to-plasma-physics-i-fall-2003/pages/lecture-notes/"
      }
    ],
    "related": [
      "poisson-laplace"
    ],
    "kind": "理论／关系",
    "editorial": "本次新增 · 附参考来源"
  },
  {
    "id": "plasma-frequency",
    "field": "等离子体",
    "topic": "集体振荡",
    "year": 1920,
    "date": "1920年代",
    "title": "电子等离子体频率",
    "people": "朗缪尔、汤克斯等",
    "formula": "ω_pe=√[n_e e²/(ε₀m_e)]",
    "summary": "电子相对近静止离子背景振荡产生特征频率。",
    "conditions": "冷、均匀、无磁等离子体的小扰动极限。",
    "variables": "ω_pe 角频率，m_e 电子质量",
    "application": "电波反射、放电诊断",
    "significance": "区分电磁波可传播和截止的典型尺度。",
    "context": "代表节点为1920年代；关键贡献者为朗缪尔、汤克斯等。该年份用于排序，不表示此前没有相关先驱工作。",
    "sources": [
      {
        "title": "MIT · Introduction to Plasma Physics I, course notes",
        "url": "https://ocw.mit.edu/courses/22-611j-introduction-to-plasma-physics-i-fall-2003/pages/lecture-notes/"
      }
    ],
    "related": [
      "em-wave",
      "debye-screening"
    ],
    "kind": "理论／关系",
    "editorial": "本次新增 · 附参考来源"
  },
  {
    "id": "cyclotron",
    "field": "等离子体",
    "topic": "单粒子运动",
    "year": 1895,
    "date": "19世纪末形成",
    "title": "回旋运动与拉莫尔半径",
    "people": "洛伦兹及后续等离子体研究者",
    "formula": "ω_c=|q|B/m，r_L=v_⊥/ω_c",
    "summary": "磁场使带电粒子的垂直速度分量产生回旋。",
    "conditions": "非相对论、均匀静磁场；相对论情形频率含 γ。",
    "variables": "q 电荷，v_⊥ 垂直速度，r_L 回旋半径",
    "application": "磁约束、回旋加速器",
    "significance": "为导引中心和磁化条件提供尺度。",
    "context": "代表节点为19世纪末形成；关键贡献者为洛伦兹及后续等离子体研究者。该年份用于排序，不表示此前没有相关先驱工作。",
    "sources": [
      {
        "title": "MIT · Introduction to Plasma Physics I, course notes",
        "url": "https://ocw.mit.edu/courses/22-611j-introduction-to-plasma-physics-i-fall-2003/pages/lecture-notes/"
      }
    ],
    "related": [
      "lorentz-force"
    ],
    "kind": "理论／关系",
    "editorial": "本次新增 · 附参考来源"
  },
  {
    "id": "exb-drift",
    "field": "等离子体",
    "topic": "单粒子运动",
    "year": 1900,
    "date": "20世纪初逐步形成",
    "title": "E×B 漂移",
    "people": "经典带电粒子理论的共同成果",
    "formula": "v_E=E×B/B²",
    "summary": "垂直电场使粒子导引中心横跨磁场漂移。",
    "conditions": "近均匀场、非相对论；E 的平行分量产生加速而非此漂移。",
    "variables": "E 电场，B 磁场，v_E 导引中心速度",
    "application": "聚变、空间等离子体",
    "significance": "此漂移与粒子质量和电荷符号无关。",
    "context": "代表节点为20世纪初逐步形成；关键贡献者为经典带电粒子理论的共同成果。该年份用于排序，不表示此前没有相关先驱工作。",
    "sources": [
      {
        "title": "MIT · Introduction to Plasma Physics I, course notes",
        "url": "https://ocw.mit.edu/courses/22-611j-introduction-to-plasma-physics-i-fall-2003/pages/lecture-notes/"
      }
    ],
    "related": [
      "cyclotron"
    ],
    "kind": "理论／关系",
    "editorial": "本次新增 · 附参考来源"
  },
  {
    "id": "vlasov",
    "field": "等离子体",
    "topic": "动理学",
    "year": 1938,
    "date": "1938 年",
    "title": "弗拉索夫方程",
    "people": "阿纳托利·弗拉索夫",
    "formula": "∂_t f+v·∇_x f+(q/m)(E+v×B)·∇_v f=0",
    "summary": "在自洽平均场中演化粒子相空间分布。",
    "conditions": "无碰撞或碰撞可忽略；E、B 与分布共同满足场方程。",
    "variables": "f(x,v,t) 分布函数",
    "application": "空间等离子体、束流、动理学模拟",
    "significance": "保留流体模型丢失的速度分布信息。",
    "context": "代表节点为1938 年；关键贡献者为阿纳托利·弗拉索夫。该年份用于排序，不表示此前没有相关先驱工作。",
    "sources": [
      {
        "title": "MIT · Introduction to Plasma Physics I, course notes",
        "url": "https://ocw.mit.edu/courses/22-611j-introduction-to-plasma-physics-i-fall-2003/pages/lecture-notes/"
      }
    ],
    "related": [
      "lorentz-force",
      "fluid-continuity"
    ],
    "kind": "理论／关系",
    "editorial": "本次新增 · 附参考来源"
  },
  {
    "id": "alfven",
    "field": "等离子体",
    "topic": "磁流体力学",
    "year": 1942,
    "date": "1942 年",
    "title": "阿尔芬波与理想 MHD",
    "people": "汉尼斯·阿尔芬",
    "formula": "v_A=B₀/√(μ₀ρ)，ω=k_∥v_A",
    "summary": "磁张力作为恢复力，使导电流体支持横向波动。",
    "conditions": "理想单流体、长波长低频、小扰动；忽略电阻耗散和相对论效应。",
    "variables": "ρ 总质量密度，k_∥ 平行波数",
    "application": "太阳风、日冕、聚变",
    "significance": "把流体运动与磁场动力学结合起来。",
    "context": "代表节点为1942 年；关键贡献者为汉尼斯·阿尔芬。该年份用于排序，不表示此前没有相关先驱工作。",
    "sources": [
      {
        "title": "MIT · Introduction to Plasma Physics I, course notes",
        "url": "https://ocw.mit.edu/courses/22-611j-introduction-to-plasma-physics-i-fall-2003/pages/lecture-notes/"
      }
    ],
    "related": [
      "maxwell",
      "euler-fluid"
    ],
    "kind": "理论／关系",
    "editorial": "本次新增 · 附参考来源"
  },
  {
    "id": "bell-chsh",
    "field": "量子信息",
    "topic": "量子关联",
    "year": 1964,
    "date": "1964 年；CHSH 1969 年",
    "title": "贝尔定理与 CHSH 不等式",
    "people": "贝尔；克劳泽、霍恩、希莫尼、霍尔特",
    "formula": "|E(a,b)+E(a,b′)+E(a′,b)−E(a′,b′)|≤2",
    "summary": "局域隐变量模型的关联有上界，量子理论可超过它。",
    "conditions": "二值测量、设置独立等假设；量子上界为 2√2，违背不等式不允许超光速传信。",
    "variables": "E 关联期望值，a、b 测量设置",
    "application": "量子基础、器件无关协议",
    "significance": "使局域隐变量假设可通过实验检验。",
    "context": "代表节点为1964 年；CHSH 1969 年；关键贡献者为贝尔；克劳泽、霍恩、希莫尼、霍尔特。该年份用于排序，不表示此前没有相关先驱工作。",
    "sources": [
      {
        "title": "Preskill · Quantum states and entanglement",
        "url": "https://www.preskill.caltech.edu/ph219/chap2_15.pdf"
      }
    ],
    "related": [
      "born-rule",
      "density-matrix"
    ],
    "kind": "理论／关系",
    "editorial": "本次新增 · 附参考来源"
  },
  {
    "id": "no-cloning",
    "field": "量子信息",
    "topic": "量子信息原理",
    "year": 1982,
    "date": "1982 年",
    "title": "量子不可克隆定理",
    "people": "伍特斯、祖雷克；迪克斯",
    "formula": "不存在对任意 |ψ⟩ 均成立的 U|ψ⟩|0⟩=|ψ⟩|ψ⟩",
    "summary": "未知的任意量子态不能被完美、确定地复制。",
    "conditions": "针对通用复制；相互正交且已知集合中的态可复制。",
    "variables": "U 酉演化，|0⟩ 辅助态",
    "application": "量子密码、量子通信",
    "significance": "约束量子信息的处理方式。",
    "context": "代表节点为1982 年；关键贡献者为伍特斯、祖雷克；迪克斯。该年份用于排序，不表示此前没有相关先驱工作。",
    "sources": [
      {
        "title": "Preskill · Quantum measurement and evolution",
        "url": "https://www.preskill.caltech.edu/ph219/chap3_15.pdf"
      }
    ],
    "related": [
      "density-matrix"
    ],
    "kind": "理论／关系",
    "editorial": "本次新增 · 附参考来源"
  },
  {
    "id": "teleportation",
    "field": "量子信息",
    "topic": "量子通信",
    "year": 1993,
    "date": "1993 年",
    "title": "量子隐形传态",
    "people": "贝内特、布拉萨尔、克雷波、若萨、佩雷斯、伍特斯",
    "formula": "共享纠缠 + 贝尔测量 + 2 个经典比特 → 单量子比特态转移",
    "summary": "通过纠缠资源和经典通信重建未知量子态。",
    "conditions": "理想协议消耗一对纠缠比特；发送方原态被测量，不能超光速。",
    "variables": "经典比特决定接收端的泡利校正",
    "application": "量子网络、量子中继",
    "significance": "转移的是状态，不是物质或额外复制。",
    "context": "代表节点为1993 年；关键贡献者为贝内特、布拉萨尔、克雷波、若萨、佩雷斯、伍特斯。该年份用于排序，不表示此前没有相关先驱工作。",
    "sources": [
      {
        "title": "Steane · Quantum Computing",
        "url": "https://arxiv.org/abs/quant-ph/9708022"
      }
    ],
    "related": [
      "bell-chsh",
      "no-cloning"
    ],
    "kind": "协议",
    "editorial": "本次新增 · 附参考来源"
  },
  {
    "id": "shor-algorithm",
    "field": "量子信息",
    "topic": "量子算法",
    "year": 1994,
    "date": "1994 年",
    "title": "Shor 算法",
    "people": "彼得·肖尔",
    "formula": "整数分解 → 模指数周期查找；复杂度 poly(log N)",
    "summary": "量子周期查找使整数分解具有多项式时间算法。",
    "conditions": "需要可扩展、足够低误差的量子电路；不是当前任意小设备都能破解实际密钥。",
    "variables": "N 待分解整数，输入长度为 log₂N",
    "application": "量子算法、密码学风险研究",
    "significance": "揭示量子计算相对已知经典方法的潜在优势。",
    "context": "代表节点为1994 年；关键贡献者为彼得·肖尔。该年份用于排序，不表示此前没有相关先驱工作。",
    "sources": [
      {
        "title": "Shor · Factoring and discrete logarithms",
        "url": "https://arxiv.org/abs/quant-ph/9508027"
      }
    ],
    "related": [
      "no-cloning"
    ],
    "kind": "算法",
    "editorial": "本次新增 · 附参考来源"
  },
  {
    "id": "grover-algorithm",
    "field": "量子信息",
    "topic": "量子算法",
    "year": 1996,
    "date": "1996 年",
    "title": "Grover 搜索算法",
    "people": "洛夫·格罗弗",
    "formula": "查询复杂度 O(√N)（唯一解）",
    "summary": "振幅放大可减少无结构搜索的查询次数。",
    "conditions": "假定相干 oracle 和唯一标记解；不包含数据库装载和 oracle 构造成本。",
    "variables": "N 候选数量，oracle 为可逆查询操作",
    "application": "搜索子程序、优化中的振幅放大",
    "significance": "提供可证明的二次查询加速。",
    "context": "代表节点为1996 年；关键贡献者为洛夫·格罗弗。该年份用于排序，不表示此前没有相关先驱工作。",
    "sources": [
      {
        "title": "Grover · Quantum database search",
        "url": "https://arxiv.org/abs/quant-ph/9605043"
      }
    ],
    "related": [
      "shor-algorithm"
    ],
    "kind": "算法",
    "editorial": "本次新增 · 附参考来源"
  },
  {
    "id": "lindblad",
    "field": "量子信息",
    "topic": "开放量子系统",
    "year": 1976,
    "date": "1976 年",
    "title": "GKSL 主方程",
    "people": "戈里尼、科萨科夫斯基、苏达尔尚；林德布拉德",
    "formula": "ρ̇=−i[H,ρ]/ℏ+Σⱼ(LⱼρLⱼ†−½{Lⱼ†Lⱼ,ρ})",
    "summary": "以保持迹和完全正性的方式描述马尔可夫耗散。",
    "conditions": "量子动力学半群或适当马尔可夫近似；不适用于所有有记忆环境。",
    "variables": "Lⱼ 跃迁算符（吸收速率因子），{,} 反对易子",
    "application": "退相干、量子光学、噪声建模",
    "significance": "为开放系统提供受数学约束的演化模型。",
    "context": "代表节点为1976 年；关键贡献者为戈里尼、科萨科夫斯基、苏达尔尚；林德布拉德。该年份用于排序，不表示此前没有相关先驱工作。",
    "sources": [
      {
        "title": "Marquardt & Püttmann · Dissipation and decoherence",
        "url": "https://arxiv.org/abs/0809.4403"
      }
    ],
    "related": [
      "density-matrix",
      "rabi"
    ],
    "kind": "理论／关系",
    "editorial": "本次新增 · 附参考来源"
  },
  {
    "id": "lyapunov",
    "field": "非线性与复杂系统",
    "topic": "混沌与稳定性",
    "year": 1892,
    "date": "1892 年稳定性理论；后续发展",
    "title": "李雅普诺夫指数",
    "people": "亚历山大·李雅普诺夫及后续动力系统研究者",
    "formula": "λ_max=lim(t→∞) t⁻¹ ln[||δx(t)||/||δx(0)||]",
    "summary": "刻画相邻轨迹的渐近指数分离率。",
    "conditions": "以切空间无穷小扰动定义；正指数须结合有界性等条件判断混沌，不能单独证明。",
    "variables": "δx 切向扰动，λ_max 最大指数",
    "application": "混沌判别、可预测性",
    "significance": "将对初值的敏感性定量化。",
    "context": "代表节点为1892 年稳定性理论；后续发展；关键贡献者为亚历山大·李雅普诺夫及后续动力系统研究者。该年份用于排序，不表示此前没有相关先驱工作。",
    "sources": [
      {
        "title": "MIT · Nonlinear Dynamics I: Chaos, course materials",
        "url": "https://ocw.mit.edu/courses/18-353j-nonlinear-dynamics-i-chaos-fall-2012/"
      }
    ],
    "related": [
      "hamilton"
    ],
    "kind": "理论／关系",
    "editorial": "本次新增 · 附参考来源"
  },
  {
    "id": "lorenz-system",
    "field": "非线性与复杂系统",
    "topic": "混沌与稳定性",
    "year": 1963,
    "date": "1963 年",
    "title": "洛伦兹混沌系统",
    "people": "爱德华·洛伦兹",
    "formula": "ẋ=σ(y−x)，ẏ=x(ρ−z)−y，ż=xy−βz",
    "summary": "确定性三维方程可产生非周期、敏感依赖初值的轨迹。",
    "conditions": "无量纲对流截断模型；行为依赖参数，不能把所有参数区间视为混沌。",
    "variables": "σ、ρ、β 参数；此处 ρ 不是密度",
    "application": "非线性教学、预测误差研究",
    "significance": "说明确定性不等于长期可预测。",
    "context": "代表节点为1963 年；关键贡献者为爱德华·洛伦兹。该年份用于排序，不表示此前没有相关先驱工作。",
    "sources": [
      {
        "title": "Lorenz (1963) · Deterministic nonperiodic flow",
        "url": "https://doi.org/10.1175/1520-0469(1963)020<0130:DNF>2.0.CO;2"
      }
    ],
    "related": [
      "lyapunov",
      "euler-fluid"
    ],
    "kind": "模型",
    "editorial": "本次新增 · 附参考来源"
  },
  {
    "id": "logistic-map",
    "field": "非线性与复杂系统",
    "topic": "分岔与映射",
    "year": 1976,
    "date": "1976 年",
    "title": "Logistic 映射与倍周期分岔",
    "people": "罗伯特·梅等；费根鲍姆发展普适性",
    "formula": "x_(n+1)=r x_n(1−x_n)",
    "summary": "一个非线性迭代规则可出现定点、周期轨道和混沌。",
    "conditions": "x∈[0,1]、0≤r≤4；1976为梅的代表性综述节点，不是该映射唯一首次出现年份。",
    "variables": "r 控制参数，n 离散步数",
    "application": "复杂系统、分岔教学",
    "significance": "揭示简单动力规则也可产生复杂行为。",
    "context": "代表节点为1976 年；关键贡献者为罗伯特·梅等；费根鲍姆发展普适性。该年份用于排序，不表示此前没有相关先驱工作。",
    "sources": [
      {
        "title": "MIT · Nonlinear Dynamics I: Chaos, course materials",
        "url": "https://ocw.mit.edu/courses/18-353j-nonlinear-dynamics-i-chaos-fall-2012/"
      }
    ],
    "related": [
      "lyapunov",
      "lorenz-system"
    ],
    "kind": "模型",
    "editorial": "本次新增 · 附参考来源"
  },
  {
    "id": "kdv",
    "field": "非线性与复杂系统",
    "topic": "孤子与非线性波",
    "year": 1895,
    "date": "1895 年方程；1965 年孤子研究",
    "title": "KdV 方程与孤子",
    "people": "科特韦赫、德弗里斯；扎布斯基、克鲁斯卡尔等",
    "formula": "u_t+6u u_x+u_xxx=0",
    "summary": "非线性陡化与色散可平衡形成稳定行波。",
    "conditions": "所示为无量纲规范形式；浅水长波、弱非线性近似的一类模型。",
    "variables": "u 波幅，x 位置，t 时间",
    "application": "浅水波、非线性波、可积系统",
    "significance": "孤子扩展了线性波叠加的图景。",
    "context": "代表节点为1895 年方程；1965 年孤子研究；关键贡献者为科特韦赫、德弗里斯；扎布斯基、克鲁斯卡尔等。该年份用于排序，不表示此前没有相关先驱工作。",
    "sources": [
      {
        "title": "Korteweg & de Vries (1895) · Long waves",
        "url": "https://doi.org/10.1080/14786449508620739"
      }
    ],
    "related": [
      "wave-equation"
    ],
    "kind": "模型",
    "editorial": "本次新增 · 附参考来源"
  },
  {
    "id": "metropolis",
    "field": "计算与数学物理",
    "topic": "统计模拟",
    "year": 1953,
    "date": "1953 年",
    "title": "Metropolis 蒙特卡洛",
    "people": "Metropolis、Rosenbluth 夫妇、Teller 夫妇",
    "formula": "A(x→x′)=min[1,exp(−βΔE)]",
    "summary": "通过随机采样估计平衡系综的平均量。",
    "conditions": "所示接受率要求对称提议分布；需遍历性、热化并估计自相关误差。",
    "variables": "ΔE 新旧能量差，β=1/(k_B T)",
    "application": "统计物理、材料模拟",
    "significance": "不必枚举全部微观态即可计算宏观量。",
    "context": "代表节点为1953 年；关键贡献者为Metropolis、Rosenbluth 夫妇、Teller 夫妇。该年份用于排序，不表示此前没有相关先驱工作。",
    "sources": [
      {
        "title": "Metropolis et al. (1953) · Equation of State Calculations",
        "url": "https://doi.org/10.1063/1.1699114"
      }
    ],
    "related": [
      "partition",
      "ising"
    ],
    "kind": "数值方法",
    "editorial": "本次新增 · 附参考来源"
  },
  {
    "id": "yee-fdtd",
    "field": "计算与数学物理",
    "topic": "场的数值计算",
    "year": 1966,
    "date": "1966 年",
    "title": "Yee 时域有限差分方法",
    "people": "Kane S. Yee",
    "formula": "∂_t B=−∇×E，∂_t D=∇×H−J → 交错网格差分",
    "summary": "在空间和时间交错采样电磁场，逐步推进麦克斯韦方程。",
    "conditions": "需满足 CFL 稳定性、足够网格分辨率与正确边界；稳定不等于准确。",
    "variables": "Δt 时间步，Δx 网格尺度，E/H 场分量",
    "application": "天线、FSS、波导、散射仿真",
    "significance": "把连续场方程变为可执行的全波数值计算。",
    "context": "代表节点为1966 年；关键贡献者为Kane S. Yee。该年份用于排序，不表示此前没有相关先驱工作。",
    "sources": [
      {
        "title": "Yee (1966) · Numerical solution of Maxwell equations",
        "url": "https://doi.org/10.1109/TAP.1966.1138693"
      }
    ],
    "related": [
      "maxwell",
      "em-wave"
    ],
    "kind": "数值方法",
    "editorial": "本次新增 · 附参考来源"
  },
  {
    "id": "verlet",
    "field": "计算与数学物理",
    "topic": "动力学模拟",
    "year": 1967,
    "date": "1967 年",
    "title": "Verlet 积分",
    "people": "Loup Verlet；此前存在相同递推思想",
    "formula": "r_(n+1)=2r_n−r_(n−1)+a_n Δt²",
    "summary": "用位置和加速度推进经典粒子轨迹。",
    "conditions": "平滑力场与合适步长；位置形式全局二阶精度，不保证任意步长下能量守恒。",
    "variables": "r_n 第 n 步位置，a_n 加速度",
    "application": "分子动力学、粒子模拟",
    "significance": "是长时间哈密顿动力学计算的重要方法。",
    "context": "代表节点为1967 年；关键贡献者为Loup Verlet；此前存在相同递推思想。该年份用于排序，不表示此前没有相关先驱工作。",
    "sources": [
      {
        "title": "Verlet (1967) · Computer experiments on classical fluids",
        "url": "https://doi.org/10.1103/PhysRev.159.98"
      }
    ],
    "related": [
      "newton-laws",
      "hamilton"
    ],
    "kind": "数值方法",
    "editorial": "本次新增 · 附参考来源"
  },
  {
    "id": "planck-spectrum",
    "field": "光学",
    "topic": "量子辐射",
    "year": 1900,
    "date": "1900 年",
    "title": "普朗克黑体辐射谱",
    "people": "马克斯·普朗克",
    "formula": "B_ν(T)=(2hν³/c²)/[exp(hν/(k_B T))−1]",
    "summary": "描述热平衡黑体的频率分辨辐亮度。",
    "conditions": "B_ν 按单位频率、单位立体角定义；波长谱不能简单把 ν 换成 c/λ。",
    "variables": "B_ν 光谱辐亮度，ν 频率，T 温度",
    "application": "红外测温、恒星谱、CMB",
    "significance": "解决经典紫外灾难并推动量子理论。",
    "context": "代表节点为1900 年；关键贡献者为马克斯·普朗克。该年份用于排序，不表示此前没有相关先驱工作。",
    "sources": [
      {
        "title": "Feynman Lectures · 统计力学原理",
        "url": "https://www.feynmanlectures.caltech.edu/I_40.html"
      },
      {
        "title": "PDG 2025 Review · 大爆炸宇宙学",
        "url": "https://pdg.lbl.gov/2025/reviews/rpp2025-rev-bbang-cosmology.pdf"
      }
    ],
    "related": [
      "planck",
      "stefan-boltzmann"
    ],
    "kind": "理论／关系",
    "editorial": "本次新增 · 附参考来源"
  },
  {
    "id": "stimulated-emission",
    "field": "光学",
    "topic": "量子光学",
    "year": 1917,
    "date": "1917 年",
    "title": "受激辐射与 Einstein 系数",
    "people": "阿尔伯特·爱因斯坦",
    "formula": "R_st=B₂₁u_ν，R_sp=A₂₁",
    "summary": "辐射场诱导激发态向低能级跃迁，产生相干放大。",
    "conditions": "两能级跃迁与谱密度约定一致；激光净增益还需考虑布居反转及损耗。",
    "variables": "A₂₁ 自发辐射率，B₂₁ 受激系数，u_ν 能量谱密度",
    "application": "激光、光放大、微波激射",
    "significance": "建立激光工作的微观基础。",
    "context": "代表节点为1917 年；关键贡献者为阿尔伯特·爱因斯坦。该年份用于排序，不表示此前没有相关先驱工作。",
    "sources": [
      {
        "title": "Feynman Lectures · 氨分子微波激射器",
        "url": "https://www.feynmanlectures.caltech.edu/III_09.html"
      }
    ],
    "related": [
      "planck-spectrum",
      "rabi"
    ],
    "kind": "理论／关系",
    "editorial": "本次新增 · 附参考来源"
  },
  {
    "id": "topological-insulator",
    "field": "凝聚态",
    "topic": "拓扑与输运",
    "year": 2005,
    "date": "2005—2007 年",
    "title": "时间反演拓扑绝缘体",
    "people": "Kane、Mele；Bernevig、Hughes、Zhang 等",
    "formula": "二维 Z₂ 指标 ν∈{0,1}",
    "summary": "体能隙与对称性保护的边缘或表面态可以共存。",
    "conditions": "所示分类用于相应时间反演对称、带隙开放的非相互作用能带体系；破坏保护对称性可开隙。",
    "variables": "ν Z₂ 拓扑指标；不是频率",
    "application": "自旋输运、拓扑器件研究",
    "significance": "把能带分类从局域结构扩展到全局拓扑。",
    "context": "代表节点为2005—2007 年；关键贡献者为Kane、Mele；Bernevig、Hughes、Zhang 等。该年份用于排序，不表示此前没有相关先驱工作。",
    "sources": [
      {
        "title": "Qi & Zhang · Topological insulators and superconductors",
        "url": "https://arxiv.org/abs/1008.2026"
      }
    ],
    "related": [
      "band-theory",
      "berry-phase"
    ],
    "kind": "理论／关系",
    "editorial": "本次新增 · 附参考来源"
  },
  {
    "id": "em-boundary",
    "field": "磁学与电磁",
    "topic": "界面与散射",
    "year": 1865,
    "date": "1865 年",
    "title": "电磁场边界条件",
    "people": "麦克斯韦场论及后续电磁学",
    "formula": "n·(D₂−D₁)=σ_f，n·(B₂−B₁)=0；n×(E₂−E₁)=0，n×(H₂−H₁)=K_f",
    "summary": "场方程在界面上给出法向和切向分量约束。",
    "conditions": "固定界面、普通电表面源且无磁表面流；n 从介质1指向介质2。",
    "variables": "σ_f 自由面电荷，K_f 自由面电流",
    "application": "介质界面、FSS、波导",
    "significance": "把材料和几何界面纳入场方程求解。",
    "context": "代表节点为1865 年；关键贡献者为麦克斯韦场论及后续电磁学。该年份用于排序，不表示此前没有相关先驱工作。",
    "sources": [
      {
        "title": "Feynman Lectures · 麦克斯韦方程",
        "url": "https://www.feynmanlectures.caltech.edu/II_18.html"
      }
    ],
    "related": [
      "maxwell",
      "fresnel-equations"
    ],
    "kind": "理论／关系",
    "editorial": "本次新增 · 附参考来源"
  },
  {
    "id": "waveguide-cutoff",
    "field": "磁学与电磁",
    "topic": "电磁波",
    "year": 1897,
    "date": "1897 年",
    "title": "矩形波导截止频率",
    "people": "瑞利等",
    "formula": "f_c,mn=(v/2)√[(m/a)²+(n/b)²]",
    "summary": "受边界约束的波导模只有高于截止频率才传播。",
    "conditions": "均匀理想导体矩形波导；v=1/√(με)，TE 模 m,n 不同时为零，TM 模两者均非零。",
    "variables": "a、b 截面尺寸，m、n 模指标",
    "application": "微波传输、滤波、腔体设计",
    "significance": "说明横向边界如何产生频率选择。",
    "context": "代表节点为1897 年；关键贡献者为瑞利等。该年份用于排序，不表示此前没有相关先驱工作。",
    "sources": [
      {
        "title": "Feynman Lectures · 波导",
        "url": "https://www.feynmanlectures.caltech.edu/II_24.html"
      }
    ],
    "related": [
      "em-boundary",
      "em-wave"
    ],
    "kind": "理论／关系",
    "editorial": "本次新增 · 附参考来源"
  },
  {
    "id": "lorentz-oscillator",
    "field": "光学",
    "topic": "色散与介质",
    "year": 1900,
    "date": "19世纪末—20世纪初",
    "title": "洛伦兹振子介电模型",
    "people": "亨德里克·洛伦兹及先驱",
    "formula": "ε_r(ω)=1+ω_p²/(ω₀²−ω²−iγω)",
    "summary": "把束缚电荷的受迫运动转化为频率相关介电响应。",
    "conditions": "采用 exp(−iωt)，线性局域单共振模型；实际材料常需多个振子。",
    "variables": "ω₀ 共振频率，γ 阻尼，ω_p² 振子强度参数",
    "application": "色散、吸收、光学材料",
    "significance": "使微观共振与宏观介电函数相连。",
    "context": "代表节点为19世纪末—20世纪初；关键贡献者为亨德里克·洛伦兹及先驱。该年份用于排序，不表示此前没有相关先驱工作。",
    "sources": [
      {
        "title": "Feynman Lectures · 致密材料的折射率",
        "url": "https://www.feynmanlectures.caltech.edu/II_32.html"
      }
    ],
    "related": [
      "drude",
      "resonance-q"
    ],
    "kind": "模型",
    "editorial": "本次新增 · 附参考来源"
  },
  {
    "id": "hubbard-model",
    "field": "凝聚态",
    "topic": "强关联电子",
    "year": 1963,
    "date": "1963 年",
    "title": "Hubbard 模型",
    "people": "约翰·哈伯德；古茨维勒、金森等",
    "formula": "H=−tΣ⟨ij⟩σ(c†ᵢσcⱼσ+h.c.)+UΣᵢnᵢ↑nᵢ↓",
    "summary": "描述电子跃迁与局域相互作用的竞争。",
    "conditions": "所示为单带、最近邻跃迁及在位相互作用模型；真实材料可能需要多轨道和长程项。",
    "variables": "t 跃迁能，U 在位相互作用，n 粒子数算符",
    "application": "莫特绝缘体、强关联与量子模拟",
    "significance": "说明独立电子近似不能解释所有固体。",
    "context": "代表节点为1963 年；关键贡献者为约翰·哈伯德；古茨维勒、金森等。该年份用于排序，不表示此前没有相关先驱工作。",
    "sources": [
      {
        "title": "Hubbard (1963) · Electron correlations in narrow energy bands",
        "url": "https://doi.org/10.1098/rspa.1963.0204"
      }
    ],
    "related": [
      "band-theory",
      "fermi-dirac"
    ],
    "kind": "模型",
    "editorial": "本次新增 · 附参考来源"
  }
];
PHYSICS_DATA.push(...additions);
})();
